# Generated by Django 4.2.1 on 2023-05-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaMovieTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinemaMovieTime_morning', models.CharField(default='', max_length=128, verbose_name='电影上映时间')),
                ('cinemaMovieTime_afternoon', models.CharField(default='', max_length=128, verbose_name='电影上映时间')),
                ('cinemaMovieTime_evening', models.CharField(default='', max_length=128, verbose_name='电影上映时间')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaMovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinemaMovie_name', models.CharField(default='', max_length=128, verbose_name='电影名字')),
                ('cinemaMovie_releaseTime', models.CharField(default='', max_length=128, verbose_name='电影上映时间')),
                ('cinemaMovie_description', models.TextField(default='', verbose_name='电影描述')),
                ('cinemaMovie_director', models.CharField(default='', max_length=128, verbose_name='电影导演')),
                ('cinemaMovie_actors', models.CharField(default='', max_length=128, verbose_name='电影演员')),
                ('cinemaMovie_movieRatings', models.CharField(default='', max_length=128, verbose_name='电影评分')),
                ('cinemaMovie_duration', models.CharField(default='', max_length=128, verbose_name='电影时长')),
                ('cinemaMovie_language', models.CharField(default='', max_length=128, verbose_name='电影语言')),
                ('cinemaMovie_country', models.CharField(default='', max_length=128, verbose_name='电影国家')),
                ('cinemaMovie_type', models.CharField(default='', max_length=128, verbose_name='电影类型')),
                ('cinemaMovie_poster', models.FileField(blank=True, default='', null=True, upload_to='CinemaMoviePoster', verbose_name='电影海报')),
                ('cinemaMovie_price', models.IntegerField(default=0, verbose_name='电影价格')),
                ('cinemaMovieTime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CinemaMovie.cinemamovietime', verbose_name='电影时间')),
            ],
        ),
    ]
