# Generated by Django 4.2.1 on 2023-05-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieclass',
            name='movies',
            field=models.ManyToManyField(blank=True, to='Movies.movieinfo', verbose_name='电影'),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_comments',
            field=models.ManyToManyField(blank=True, to='Movies.moviecomment', verbose_name='电影评论'),
        ),
    ]
