# Generated by Django 4.2.1 on 2023-05-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_alter_movieclass_movies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieclass',
            old_name='movies',
            new_name='movies_class_movie',
        ),
    ]
