# Generated by Django 4.2.1 on 2023-05-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_rename_movies_movieclass_movies_class_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='movie_comments',
            new_name='movie_comment',
        ),
    ]
