# Generated by Django 4.2.1 on 2023-05-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_rename_movie_comments_movieinfo_movie_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieclass',
            old_name='movies_class_movie',
            new_name='movie_class_movie',
        ),
    ]
