# Generated by Django 4.2.1 on 2023-05-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0005_rename_movies_class_movie_movieclass_movie_class_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='movie_url',
            field=models.CharField(default='', max_length=128, verbose_name='电影播放地址'),
        ),
    ]
