# Generated by Django 4.2.1 on 2023-05-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=128, verbose_name='用户名')),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('user_tel', models.CharField(default='', max_length=11, unique=True, verbose_name='电话号码')),
                ('user_sex', models.CharField(max_length=20, verbose_name='性别')),
                ('user_old', models.CharField(max_length=128, verbose_name='年龄')),
                ('user_avatar', models.FileField(blank=True, default='', null=True, upload_to='UserAvatar', verbose_name='用户头像')),
            ],
            options={
                'verbose_name': 'UserInformation',
                'verbose_name_plural': 'UserInformation',
            },
        ),
        migrations.CreateModel(
            name='UserPlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPlayList_Movie', models.ManyToManyField(blank=True, null=True, to='Movies.movieinfo', verbose_name='user play list movie')),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userComment', models.ManyToManyField(blank=True, null=True, to='Movies.moviecomment', verbose_name='user comment')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, unique=True, verbose_name='user name')),
                ('user_password', models.CharField(max_length=256, verbose_name='user password')),
                ('user_createTime', models.DateTimeField(auto_now_add=True, verbose_name='user create time')),
                ('user_loginState', models.CharField(default='', max_length=100, verbose_name='user login state')),
                ('user_userInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='UserAccount.userinfo', verbose_name='user information')),
            ],
            options={
                'verbose_name': 'UserAccount',
                'verbose_name_plural': 'UserAccount',
                'ordering': ['user_createTime'],
            },
        ),
    ]
