# Generated by Django 4.2.1 on 2023-05-24 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0002_alter_usercomment_usercomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_userComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='UserAccount.usercomment', verbose_name='user comment'),
        ),
    ]
