# Generated by Django 4.2.1 on 2023-05-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0003_useraccount_user_usercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='userComment',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='movie_comment_content',
            field=models.TextField(default='', verbose_name='评论内容'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='movie_comment_dislike',
            field=models.IntegerField(default=0, verbose_name='评论点踩数'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='movie_comment_like',
            field=models.IntegerField(default=0, verbose_name='评论点赞数'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='movie_comment_movieName',
            field=models.CharField(default='', max_length=128, verbose_name='评论电影名字'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='movie_comment_time',
            field=models.TextField(default='', verbose_name='评论时间'),
        ),
    ]
