# Generated by Django 4.2.1 on 2023-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0004_remove_usercomment_usercomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_userComment',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_userComment',
            field=models.ManyToManyField(blank=True, to='UserAccount.usercomment', verbose_name='user comment'),
        ),
    ]
